language: generic

sudo: required
services:
  - docker 

before_install:
  - docker build -t liangmin1215/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true liangmin1215/docker-react npm run test -- --coverage